name: Rust

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build_static_linux_binary:
    name: "Build static Linux binary"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build-musl
      uses: gmiam/rust-musl-action@master
      with:
        args: cargo build --target x86_64-unknown-linux-gnu	--release
    - uses: actions/upload-artifact@v2
      with:
        name: fnm-linux-gnu
        path: target/x86_64-unknown-linux-gnu/release/fnm
