name: Rust

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
    - uses: actions/checkout@v2
    - name: cargo fmt
      run: cargo fmt -- --check

#   unit_tests:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         os: [ubuntu-latest]
#     steps:
#     - uses: hecrj/setup-rust-action@v1
#       with:
#         rust-version: stable
#     - uses: actions/checkout@v2
#     - name: Run tests
#       run: cargo test -- --skip=feature_tests

#   e2e_tests:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         os: [ubuntu-latest]
#     steps:
#     - name: Install Fish and Zsh using apt
#       if: "startsWith(matrix.os, 'ubuntu')"
#       run: sudo apt-get install -y fish zsh
#     - uses: hecrj/setup-rust-action@v1
#       with:
#         rust-version: stable
#     - uses: actions/checkout@v2
#     - name: Run tests
#       run: cargo test -- feature_tests

  build_static_linux_binary:
    name: "Build static Linux binary"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build static binary
      run: |
        sudo chown -R 1000:1000 .
        docker run --rm -v "$(pwd)":/home/rust/src ekidd/rust-musl-builder:stable \
          cargo build --release
        sudo chown -R $(whoami):$(whoami) .
    - uses: actions/upload-artifact@v2
      with:
        name: fnm-linux
        path: target/x86_64-unknown-linux-musl/release/fnm
